### ISSUE TITLE
画面モック作成

### ISSUE THREAD

**Issue by jacoloves** [naokillme2021/zen-yomi#19]
Adobeで作成予定
https://www.adobe.com/jp/products/xd.html

**Comment by jacoloves** [comment]
# たたき台モック画面を作成
<img width="1440" alt="スクリーンショット 2020-02-19 0 57 10" src="https://user-images.githubusercontent.com/14506513/74753087-f4075900-52b2-11ea-9f72-97dcc4da7848.png">

**Comment by jacoloves** [comment]
@naokillme2021 
レビューよろしくおねがいします。

**Comment by nmatsumoto4274** [comment]
@jacoloves ニュースをリストで表示良きですね！
ネガポジの表現方法について相談させてください。（色 、アイコン、etc...）

**Comment by jacoloves** [comment]
@naokillme2021 

> ニュースをリストで表示良きですね！

ありがとうございます。

>ネガポジの表現方法について相談させてください。（色 、アイコン、etc...）

そこはぜひ相談したいです。ネガポジは重要な部分になるので何かアイデアあればください。
ネガポジ決まってモック反映→レビュー終わり次第画面遷移図の作成の話をしたいです。

**Comment by nmatsumoto4274** [comment]
> ネガポジは重要な部分になるので何かアイデアあればください。

自分の持っている案としては、以下になります。
* 見出しに顔アイコンや画像を付与する
* 各ニュースの背景色で区別（ポジティブは赤背景、ネガティブは青背景など）
* 見出しの文字色で区別
背景色は文字色との兼ね合いがあるため、ちょっと見づらいかもですね。

**Comment by jacoloves** [comment]
@naokillme2021 

>見出しに顔アイコンや画像を付与する

これはよさそうですね！
ニコちゃんマークとがっかりマーク的な感じで判断してもらうのはいいかもしれないです。

・これはジャストアイデアなんですが、初めからネガポジで何かしらの住み分けされてると仮定してネガポジで別々のニュースリストが出てくるのはどうでしょうか。（要するに2つニュースリストが並ぶイメージ）

**Comment by jacoloves** [comment]
かなり雑にはなりますがざっくりイメージです。

![サンプルイメージ（ポジネガ）](https://user-images.githubusercontent.com/14506513/74802487-5eed7a00-531d-11ea-8e7c-82b4baf2d0e6.PNG)

**Comment by nmatsumoto4274** [comment]
> ネガポジで別々のニュースリストが出てくるのはどうでしょうか。

良いと思います！このWebアプリは1行に要約されたニュースをたくさん表示して、できるだけ多くのニュースに目を通せる事が目的なので、画像のように２列で表示が良いかもです。

**Comment by jacoloves** [comment]
@naokillme2021 

xdファイル開けなかったとき用に画像も貼っときます。
<img width="1440" alt="スクリーンショット 2020-02-20 22 42 47" src="https://user-images.githubusercontent.com/14506513/74939135-b7fb0200-5432-11ea-9143-2225927da86e.png">
